# node-stage
FROM node:16.17.1 as builder

WORKDIR '/usr/src/app'

COPY package.json .
COPY package-lock.json ./

RUN npm install -g npm@8.19.2
RUN npm install -f

COPY ./ ./

RUN npx tailwindcss --yes -i ./src/input.css -o ./dist/output.css
RUN npm run build

# nginx-stage
FROM nginx:1.13
EXPOSE 80

RUN rm /etc/nginx/conf.d/default.conf
COPY ./default.conf /etc/nginx/conf.d

RUN rm /usr/share/nginx/html/index.html
COPY --from=builder /usr/src/app/dist /usr/share/nginx/html
